language: c
os:
  - linux
  - osx
dist: xenial

# try to build:
script: ./configure && make && make check
# (once the testsuite is fixed for VPATH builds, we can do distcheck, too)

compiler:
  - clang
  - gcc
