---
name: cooljeanius/mdnsd
on:
  push:
    branches:
      - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v5
        # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are
        # currently unsupported
        # 'compiler' was not transformed because there is no suitable equivalent
        # in GitHub Actions
      - run: "./configure CC=${{ matrix.compiler }} && make && make check"
      # TODO: add distcheck
      # (currently fails with: testsuite: error: cannot find ../mhttp)
    strategy:
      matrix:
        compiler:
          - clang
          - gcc
        os:
          - ubuntu-latest
          - macos-latest
